INSERT INTO CLIENTES(NOME, SENHA) VALUES('IGOR', '123455');
INSERT INTO CLIENTES(NOME, SENHA) VALUES('RAFAELA', '4242313');
INSERT INTO CLIENTES(NOME, SENHA) VALUES('NEIDHA', '249249274');

INSERT INTO PRODUTOS(NOME, QUANTIDADE) VALUES('JACA', 10);
INSERT INTO PRODUTOS(NOME, QUANTIDADE) VALUES('MAÇA', 15);
INSERT INTO PRODUTOS(NOME, QUANTIDADE) VALUES('BANANA', 20);

INSERT INTO VENDEDORES(NOME, SENHA) VALUES('VINI', '18638173');
INSERT INTO VENDEDORES(NOME, SENHA) VALUES('DAVID', '1314242');