INSERT INTO CLIENTES(NOME, IDADE) VALUES('IGOR', 29);
INSERT INTO CLIENTES(NOME, IDADE) VALUES('RAFAELA', 28);

INSERT INTO VENDEDORES(NOME, IDADE) VALUES('DAVID', 22);
INSERT INTO VENDEDORES(NOME, IDADE) VALUES('VINI', 25);

INSERT INTO PRODUTOS(NOME, QUANTIDADE, TIPO) VALUES('CELULAR', 30, 'ELETRONICOS');
INSERT INTO PRODUTOS(NOME, QUANTIDADE, TIPO) VALUES('COMPUTADOR', 30, 'ELETRONICOS');