INSERT INTO CLIENTES(NOME, SENHA) VALUES('IGOR', '12345');
INSERT INTO CLIENTES(NOME, SENHA) VALUES('RAFA', '42315');
INSERT INTO CLIENTES(NOME, SENHA) VALUES('NUBIA', '52444');

INSERT INTO LIVROS(NOME, TITTLE, QUANTIDADE) VALUES('DOM QUIXOTE', 'DE LA MANCHA', 10);
INSERT INTO LIVROS(NOME, TITTLE, QUANTIDADE) VALUES('HARRY POTTER', 'CALICE DE FOGO', 2);
INSERT INTO LIVROS(NOME, TITTLE, QUANTIDADE) VALUES('KARL MARX', 'O CAPITAL', 1);